#!/usr/bin/env bash
# Put a `pidash` command on PATH that runs THIS checkout's release build.
#
#   ./install.sh                 -> /usr/local/bin/pidash   (needs root)
#   ./install.sh ~/.local/bin    -> ~/.local/bin/pidash     (no root)
#
# A wrapper rather than a copy of the binary, so `cargo build --release` here
# is immediately what `pidash` runs. Copying means every rebuild silently keeps
# launching the previous build, which is a genuinely confusing way to lose an
# afternoon.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$HERE/target/release/pi-dash"
DEST_DIR="${1:-/usr/local/bin}"
DEST="$DEST_DIR/pidash"

if [[ ! -x "$BIN" ]]; then
    echo "no release build at $BIN" >&2
    echo "build it first:  cd $HERE && cargo build --release" >&2
    exit 1
fi

if [[ ! -d "$DEST_DIR" ]]; then
    echo "$DEST_DIR does not exist" >&2
    exit 1
fi

if [[ ! -w "$DEST_DIR" ]]; then
    echo "$DEST_DIR is not writable -- re-run with sudo, or pass a directory" >&2
    echo "you own:  ./install.sh ~/.local/bin" >&2
    exit 1
fi

cat > "$DEST" <<EOS
#!/usr/bin/env bash
# Generated by pi-dash/install.sh -- runs the release build in the checkout at
# $HERE, so a rebuild there takes effect here with no reinstall.
exec "$BIN" "\$@"
EOS
chmod +x "$DEST"

echo "installed $DEST -> $BIN"

# A wrapper on PATH that is shadowed by an earlier one is the other confusing
# way to lose an afternoon.
found="$(command -v pidash 2>/dev/null || true)"
if [[ -n "$found" && "$found" != "$DEST" ]]; then
    echo "warning: '$found' comes first on PATH and will win over $DEST" >&2
fi
