#!/usr/bin/env bash
# Put a `pidash` command on PATH that runs THIS checkout's release build.
#
#   ./install.sh                 -> /usr/local/bin/pidash   (needs root)
#   ./install.sh ~/.local/bin    -> ~/.local/bin/pidash     (no root)
#
# A wrapper rather than a copy of the binary, so `cargo build --release` here
# is immediately what `pidash` runs. Copying means every rebuild silently keeps
# launching the previous build, which is a genuinely confusing way to lose an
# afternoon.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$HERE/target/release/pi-dash"
DEST_DIR="${1:-/usr/local/bin}"

if [[ ! -x "$BIN" ]]; then
    echo "no release build at $BIN" >&2
    echo "build it first:  cd $HERE && cargo build --release" >&2
    exit 1
fi

if [[ ! -d "$DEST_DIR" ]]; then
    echo "$DEST_DIR does not exist" >&2
    exit 1
fi

# Resolved before anything prints or compares it. `./install.sh ~/.local/bin/`
# and `./install.sh ./bin` both name a perfectly good directory and both used
# to produce a path that could never match what `command -v` reports -- so the
# shadow check at the bottom fired on the file it had just written and warned
# that the install would lose to itself.
DEST_DIR="$(cd "$DEST_DIR" && pwd)"
DEST="$DEST_DIR/pidash"

if [[ ! -w "$DEST_DIR" ]]; then
    echo "$DEST_DIR is not writable -- re-run with sudo, or pass a directory" >&2
    echo "you own:  ./install.sh ~/.local/bin" >&2
    exit 1
fi

cat > "$DEST" <<EOS
#!/usr/bin/env bash
# Generated by pi-dash/install.sh -- runs the release build in the checkout at
# $HERE, so a rebuild there takes effect here with no reinstall.
exec "$BIN" "\$@"
EOS
chmod +x "$DEST"

echo "installed $DEST -> $BIN"

# Installing somewhere PATH does not look is the quietest way to lose an
# afternoon: the install reports success and the command does not exist.
case ":$PATH:" in
    *":$DEST_DIR:"*) ;;
    *)
        echo "warning: $DEST_DIR is not on your PATH, so 'pidash' will not be found" >&2
        echo "add it:  echo 'export PATH=\"$DEST_DIR:\$PATH\"' >> ~/.bashrc" >&2
        ;;
esac

# A wrapper on PATH that is shadowed by an earlier one is the other confusing
# way to lose an afternoon.
found="$(command -v pidash 2>/dev/null || true)"
if [[ -n "$found" && "$found" != "$DEST" ]]; then
    echo "warning: '$found' comes first on PATH and will win over $DEST" >&2
fi
